nome = input("Nome: ")
idade = input("Idade: ")
curso = input("Curso: ")
evento = input("Evento: ")
print(f"Confirmado! {nome}, {idade} anos, estudante de {curso}, está inscrito no evento {evento}.")